# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glider',
            name='glide_ratio',
            field=models.FloatField(),
        ),
    ]
