# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20170613_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='glider',
            name='best_glide_speed',
            field=models.IntegerField(default=0),
        ),
    ]
